version: '3'
services:
  nginx:
    build: ./nginx
    links:
      - core:core
    ports:
      - "8080:8080"
    volumes:
      - js-assets:/data/www/js
      - ./dashboard/resources/public:/data/www
  core:
    build: ./core
    ports:
      - "31778"
  dashboard:
    build: ./dashboard
    volumes:
      - js-assets:/usr/src/app/resources/public/js
volumes:
  js-assets:
    driver: local
